inherits = "base16_transparent"

"ui.background" = {}

[palette]
white = "#DFDFE0"
lilac = "#BE95FF"
lavender = "#78A9FF"
comet = "#33B1FF"
bossanova = "#282828"
midnight = "#161616"
revolver = "#161616"

silver = "#F2F4F8"
sirocco = "#697C81"
mint = "#25BE6A"
almond = "#ECC5BA" # Ajustado derivado para tonos cálidos
chamois = "#08BDBA"
honey = "#BEA165" # Derivado cálido

apricot = "#EE5396"
lightning = "#FFD700" # Relacionado con el amarillo brillante
delta = "#6F44F0" # Queda como un placeholder adicional similar al púrpura original
