# [opener]
# edit = [
# { run = "%EDITOR% %*",  block = true, for = "windows" },
# { run = '$EDITOR "$@"', block = true, for = "unix" },
# ]
# open = [
#   { run = "%EDITOR% %*", desc = "open", for = "windows"},
# ]
#
# [open]
# prepend_rules = [
#     { name = "*.ps1", use = "edit" },
# ]
# append_rules = [
#     { name = "*", use = "edit" },
# ]
#

[opener]
edit = [
{ run = "${EDITOR} \"$@\"", block = true, orphan = false, desc = "$EDITOR", for = "unix", spread = true },
]

