
[window]
opacity = 0.7

[keyboard]
bindings = [
{key = "T", mods = "Control|Shift", action = "SpawnNewInstance"},
{key = "T", mods = "Super|Shift", action = "SpawnNewInstance"},
]

[general]
import = [
    "~/.config/alacritty/color/carbonfox.toml",
    "~/.config/alacritty/font/base.toml",
]
